### ISSUE TITLE
Using on windows

### ISSUE THREAD

**Issue by radimkohout** [QuasarApp/Qt-Secret#59]
Hi,
how can I use this library in qt creator on windows? I can't do it.
Thanks
Radim Kohout

**Comment by EndrII** [comment]
Hi 

For the correct incude you need:

## incude in qtCreator 
* Open QtCreator
* Create a new subdirs project (file >> create new project of file >> other projects >> subdirs project) and call it 'Master'
* Copy **your project folder** into **the Master project folder** or if you use git then add your project like submodule of master poject. Use command: "git submodules add **URL**"
 * Open Master.pro and add your project like subproject
``` qmake
SUBDIRS += \
           youProjectFolder

youProjectFolder.file = path/to/yuorProject.pro
```
 * Open the Master project folder in git console. If git not install then install it [this](https://git-scm.com/download/win)
 * run: git submodule add https://github.com/QuasarApp/Qt-Secret.git 
 * run: git submodule update --init --recursive
 * Open Master.pro
 * Add Qt-Secret library like submproject of Master
``` qmake
SUBDIRS += \
           youProjectFolder \
          Qt-Secret \

youProjectFolder.file = path/to/yuorProject.pro
``` 
 * Open YouProject.pro
 * Include in your MyProject.pro file the pri file of Qt-Secret library (insert ito end of file next line :)
``` qmake
 include($$PWD/../Qt-Secret/src/Qt-Secret.pri)

```
 * Rebuild Master project
 * All done!. Now you nead to build only master project, because it will build both your project and the project Qt-Secret. QT-Secret will already be included to your project and you will be able to use it in your code. 


For Example you can see my [master](https://github.com/QuasarApp/Qt-Secret/blob/master/Qt-Secret.pro) project and incude library [lines](https://github.com/QuasarApp/Qt-Secret/blob/a6828ea53d8b6a5f60def149fee2792ae6d7d774/Qt-Secret-GUI/Qt-Secret-GUI.pro#L22).

**Comment by EndrII** [comment]
@radimkohout if this instruction helped. i Add it to README file.
let me know what you got as a result.

**Comment by radimkohout** [comment]
It works( You forgot to use "git init")

**Comment by EndrII** [comment]
No. I am use "git submodule update --init --recursive"
this command initializes along with a full upgrade.

can i close the topic?

**Comment by radimkohout** [comment]
Nope, when I use QRSAEncryption e(QRSAEncryption::Rsa::RSA_2048);
13:36:24: The program has unexpectedly finished.
13:36:24: The process was ended forcefully.

**Comment by EndrII** [comment]
@radimkohout 
Yes. This is not a valid example. I updated README.
See a new example :
``` cpp
#include <qrsaencryption.h>
#include <QDebug>

bool testEncryptAndDecryptExample() {

    QByteArray pub, priv;
    QRSAEncryption e(QRSAEncryption::Rsa::RSA_2048);
    e.generatePairKey(pub, priv); // or other rsa size

    QByteArray msg = "test message";

    auto encryptMessage = e.encode(msg, pub);

    if (encryptMessage == msg)
        return false;

    auto decodeMessage = e.decode(encryptMessage, priv);

    return decodeMessage == msg;
}

int main() {
    if (testEncryptAndDecryptExample()) {
        qInfo() << "Success!";
    }
}
```

**Comment by radimkohout** [comment]
Not better. This is my code:
`#include "mainwindow.h"
#include <QApplication>
#include "myserver.h"
#include <QObject>
#include <QDebug>
#include <qrsaencryption.h>
bool testEncryptAndDecryptExample() {

    QByteArray pub, priv;
    QRSAEncryption e(QRSAEncryption::Rsa::RSA_2048);
    e.generatePairKey(pub, priv); // or other rsa size

    QByteArray msg = "test message";

    auto encryptMessage = e.encode(msg, pub);

    if (encryptMessage == msg)
        return false;

    auto decodeMessage = e.decode(encryptMessage, priv);

    return decodeMessage == msg;
}
int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
    MainWindow w;
    w.show();
    MyServer S;
    if (testEncryptAndDecryptExample()) {
            qInfo() << "Success!";
        }
return a.exec();
}
`
The only thing I am getting are 37 warnings like this:
`
Makefile.GMP:80: warning: ignoring old recipe for target 'sub-tests-tests-pro-qmake_all'
`

**Comment by EndrII** [comment]
Show me your build log or give me your repository with your code. So that I can find a problem.

**Comment by radimkohout** [comment]
https://github.com/radimkohout/RServer/

**Comment by EndrII** [comment]
Sorry, I made some mistakes when writing the instructions, it’s important for us to build the dependencies first and then only your project.
I updated the instructions. You need to rewrite your Master.pro with instructions


# incude Qt-Secret in qtCreator 
* Open QtCreator
* Create a new subdirs project (file >> create new project of file >> other projects >> subdirs project) and call it 'Master'
* Copy **your project folder** into **the Master project folder** or if you use git then add your project like submodule of master poject. Use command: "git submodules add **URL**"
* Open Master.pro and add your project like subproject

``` qmake
TEMPLATE = subdirs
CONFIG += ordered

SUBDIRS += \
           youProjectFolder

youProjectFolder.file = path/to/yuorProject.pro
```
 * Open the Master project folder in git console. If git not install then install it [this](https://git-scm.com/download/win)
 * run: git submodule add https://github.com/QuasarApp/Qt-Secret.git 
 * run: git submodule update --init --recursive
 * Open Master.pro
 * Add Qt-Secret library like submproject of Master
``` qmake
TEMPLATE = subdirs
CONFIG += ordered

SUBDIRS += \
           Qt-Secret \
           youProjectFolder \

youProjectFolder.file = path/to/yuorProject.pro
``` 
 * Open YouProject.pro
 * Include in your MyProject.pro file the pri file of Qt-Secret library (insert ito end of file next line :)
``` qmake
 include($$PWD/../Qt-Secret/src/Qt-Secret.pri)

```
 * Rebuild Master project
 * All done!. Now you nead to build only master project, because it will build both your project and the project Qt-Secret. QT-Secret will already be included to your project and you will be able to use it in your code. 


For Example you can see my [master](https://github.com/QuasarApp/Qt-Secret/blob/master/Qt-Secret.pro) project and incude library [lines](https://github.com/QuasarApp/Qt-Secret/blob/a6828ea53d8b6a5f60def149fee2792ae6d7d774/Qt-Secret-GUI/Qt-Secret-GUI.pro#L22).

**Comment by EndrII** [comment]
jusy add 
``` qmake
TEMPLATE = subdirs
CONFIG += ordered

```
and swap Qt-Secret and YourProjectFolder. So that Qt-Secret would be the first.

**Comment by radimkohout** [comment]
Fixed... See my repo. But I am getting another error:
`
error: [Makefile:133: sub-youProjectFolder-file-make_first-ordered] Error 2
`

**Comment by EndrII** [comment]
you forgot about CONFIG + = ordered
in master.pro
```
TEMPLATE = subdirs
CONFIG += ordered
```

**Comment by radimkohout** [comment]
Nope, it was one-time compilation error. Rebuild, and it works. 
Thanks. Everything's working.

**Comment by EndrII** [comment]
@radimkohout 
it is still extremely important for you to add 'CONFIG + = ordered' because this configuration forces qmake to build the projects in the order you specify. If this setting does not exist, then you will now receive periodically compilation errors.

**Comment by radimkohout** [comment]
I have It there.
